# Generated by Django 5.1.7 on 2025-03-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.URLField(blank=True, default='', null=True)),
                ('listeners', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('link', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Non-binary', 'Non-binary')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('image', models.URLField(blank=True, default='', null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_back.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, default='', null=True)),
                ('music_file', models.FileField(upload_to='music/')),
                ('fullscreen_image', models.FileField(blank=True, default='', null=True, upload_to='image/')),
                ('duration', models.CharField(max_length=10)),
                ('plays', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_back.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_back.artist')),
            ],
        ),
    ]
