# Generated by Django 5.1.7 on 2025-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_back', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='fullscreen_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
