# Generated by Django 5.1.7 on 2025-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_back', '0004_alter_song_fullscreen_image_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='fullscreen_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
